isProd: false

server:
  port: 8083

my:
  swagger:
    prefix:

spring:
  application:
    name: prediction
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: true

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

---
spring:
  profiles: prod

my:
  swagger:
    prefix: /prediction

isProd: true