apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
        - image: blarc/rso-prediction:95caf65
          name: prediction
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 180
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 180
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: prediction
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: prediction