server:
  port: ${PORT:8083}

isProd: ${IS_PROD:false}

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/ztjjveon
    username: ztjjveon
    password: JeprpBJVCH94DZV-XmWXAPHkHTUeHdiX
    driverClassName: org.postgresql.Driver